service: kamal-prometheus-example
image: lewispb/kamal-prometheus-example

servers:
  - 5.75.133.65

registry:
  username: lewispb
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
