service: kamal-prometheus-example
image: lewispb/kamal-prometheus-example


servers:
  web:
    hosts:
      - 5.75.133.65

registry:
  username: lewispb
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

# Prometheus metrics with OpenTelemetry Collector
accessories:
  otel_collector:
    image: otel/opentelemetry-collector:0.100.0
    port: 9394
    files:
      - config/otel_collector.yml:/etc/otelcol/config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    options:
      user: 0
    roles:
      - web
      # - jobs
